// Tiered, country-based registration pricing.
// Source: organizers' "website_updates_august12" brief. The discount applies to
// the participant's early-bird or regular fee from `@/lib/fees`.

export type TierId = 1 | 2 | 3;

export type CountryTier = {
  id: TierId;
  label: string;
  /** Discount off the corresponding early-bird or regular fee. */
  discount: string;
  /** Empty for Tier 1, which is defined by exclusion — see TIER_1_RULE. */
  countries: string[];
};

export const TIER_1_RULE = "All countries not listed under Tier 2 or Tier 3.";

export const COUNTRY_TIERS: CountryTier[] = [
  {
    id: 1,
    label: "Tier 1",
    discount: "0% (standard rate)",
    countries: [],
  },
  {
    id: 2,
    label: "Tier 2",
    discount: "20%",
    countries: [
      "Albania",
      "Algeria",
      "Argentina",
      "Armenia",
      "Azerbaijan",
      "Belarus",
      "Belize",
      "Bosnia and Herzegovina",
      "Botswana",
      "Brazil",
      "Cabo Verde",
      "China",
      "Colombia",
      "Cuba",
      "Dominican Republic",
      "Ecuador",
      "El Salvador",
      "Equatorial Guinea",
      "Fiji",
      "Gabon",
      "Georgia",
      "Guatemala",
      "Indonesia",
      "Iran (Islamic Republic of)",
      "Iraq",
      "Jamaica",
      "Kazakhstan",
      "Libya",
      "Malaysia",
      "Maldives",
      "Mauritius",
      "Mexico",
      "Mongolia",
      "Montenegro",
      "North Macedonia",
      "Paraguay",
      "Peru",
      "Republic of Moldova",
      "Samoa",
      "Serbia",
      "South Africa",
      "Suriname",
      "Thailand",
      "Türkiye",
      "Turkmenistan",
      "Ukraine",
    ],
  },
  {
    id: 3,
    label: "Tier 3",
    discount: "40%",
    countries: [
      "Afghanistan",
      "Angola",
      "Bangladesh",
      "Benin",
      "Bhutan",
      "Bolivia (Plurinational State of)",
      "Burkina Faso",
      "Burundi",
      "Cambodia",
      "Cameroon",
      "Central African Republic",
      "Chad",
      "Comoros",
      "Congo",
      "Côte d'Ivoire",
      "Democratic People's Republic of Korea",
      "Democratic Republic of the Congo",
      "Djibouti",
      "Egypt",
      "Eritrea",
      "Eswatini",
      "Gambia",
      "Ghana",
      "Guinea",
      "Guinea-Bissau",
      "Haiti",
      "Honduras",
      "India",
      "Jordan",
      "Kenya",
      "Kiribati",
      "Kyrgyzstan",
      "Lao People's Democratic Republic",
      "Lebanon",
      "Lesotho",
      "Liberia",
      "Madagascar",
      "Malawi",
      "Mali",
      "Mauritania",
      "Morocco",
      "Mozambique",
      "Myanmar",
      "Namibia",
      "Nepal",
      "Nicaragua",
      "Niger",
      "Nigeria",
      "Pakistan",
      "Papua New Guinea",
      "Philippines",
      "Rwanda",
      "Sao Tome and Principe",
      "Senegal",
      "Sierra Leone",
      "Solomon Islands",
      "Somalia",
      "South Sudan",
      "Sri Lanka",
      "State of Palestine",
      "Sudan",
      "Syrian Arab Republic",
      "Tajikistan",
      "Timor-Leste",
      "Togo",
      "Tunisia",
      "Uganda",
      "United Republic of Tanzania",
      "Uzbekistan",
      "Vanuatu",
      "Viet Nam",
      "Yemen",
      "Zambia",
      "Zimbabwe",
    ],
  },
];

export const WESP_SOURCE =
  "Country classifications are drawn directly from Table E (per capita GNI classification, " +
  "as at 1 July 2025) of the Statistical Annex of the United Nations World Economic Situation " +
  "and Prospects (WESP) 2026 report.";
